TEST_VALUE:
  name: cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a271c88881fdd00b
  FEISHU_APP_SECRET: a6527NXeY512uoQnASqBbhr7ppjckTra
  APP_TOKEN_CACHE_KEY:
MONGODB_CONFIG:
  name: 'fast_gateway_test' # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: 'mongodb://localhost:27017' # 数据库链接地址
  username: 'xxxx' # 数据库链接用户名
  password: '123456' # 数据库链接密码
  database: 'fast_gateway_test' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: 'mysql'
  type: 'mysql'
  host: '118.89.107.19'
  port: 3306
  username: 'money_note'
  password: ''
  database: 'money_note'
  entities: 'mysql' # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true
