TEST_VALUE:
  name: cookie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a270ac480a73500b
  FEISHU_APP_SECRET: pwwlmPF71nL4oCWzFYu5GgVTnuN2SlhV
